// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package agentero

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommsClient is the client API for Comms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommsClient interface {
	CredentialSystem(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogReply, error)
	GetContactAndPoliciesById(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*ContactAndPolicies, error)
	GetContactsAndPoliciesByMobileNumber(ctx context.Context, in *MobileNumber, opts ...grpc.CallOption) (*ContactAndPolicies, error)
}

type commsClient struct {
	cc grpc.ClientConnInterface
}

func NewCommsClient(cc grpc.ClientConnInterface) CommsClient {
	return &commsClient{cc}
}

func (c *commsClient) CredentialSystem(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogReply, error) {
	out := new(LogReply)
	err := c.cc.Invoke(ctx, "/agentero.Comms/CredentialSystem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsClient) GetContactAndPoliciesById(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*ContactAndPolicies, error) {
	out := new(ContactAndPolicies)
	err := c.cc.Invoke(ctx, "/agentero.Comms/GetContactAndPoliciesById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsClient) GetContactsAndPoliciesByMobileNumber(ctx context.Context, in *MobileNumber, opts ...grpc.CallOption) (*ContactAndPolicies, error) {
	out := new(ContactAndPolicies)
	err := c.cc.Invoke(ctx, "/agentero.Comms/GetContactsAndPoliciesByMobileNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommsServer is the server API for Comms service.
// All implementations must embed UnimplementedCommsServer
// for forward compatibility
type CommsServer interface {
	CredentialSystem(context.Context, *LogRequest) (*LogReply, error)
	GetContactAndPoliciesById(context.Context, *UserID) (*ContactAndPolicies, error)
	GetContactsAndPoliciesByMobileNumber(context.Context, *MobileNumber) (*ContactAndPolicies, error)
	mustEmbedUnimplementedCommsServer()
}

// UnimplementedCommsServer must be embedded to have forward compatible implementations.
type UnimplementedCommsServer struct {
}

func (UnimplementedCommsServer) CredentialSystem(context.Context, *LogRequest) (*LogReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CredentialSystem not implemented")
}
func (UnimplementedCommsServer) GetContactAndPoliciesById(context.Context, *UserID) (*ContactAndPolicies, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContactAndPoliciesById not implemented")
}
func (UnimplementedCommsServer) GetContactsAndPoliciesByMobileNumber(context.Context, *MobileNumber) (*ContactAndPolicies, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContactsAndPoliciesByMobileNumber not implemented")
}
func (UnimplementedCommsServer) mustEmbedUnimplementedCommsServer() {}

// UnsafeCommsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommsServer will
// result in compilation errors.
type UnsafeCommsServer interface {
	mustEmbedUnimplementedCommsServer()
}

func RegisterCommsServer(s grpc.ServiceRegistrar, srv CommsServer) {
	s.RegisterService(&Comms_ServiceDesc, srv)
}

func _Comms_CredentialSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).CredentialSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agentero.Comms/CredentialSystem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).CredentialSystem(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comms_GetContactAndPoliciesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).GetContactAndPoliciesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agentero.Comms/GetContactAndPoliciesById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).GetContactAndPoliciesById(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comms_GetContactsAndPoliciesByMobileNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MobileNumber)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).GetContactsAndPoliciesByMobileNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agentero.Comms/GetContactsAndPoliciesByMobileNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).GetContactsAndPoliciesByMobileNumber(ctx, req.(*MobileNumber))
	}
	return interceptor(ctx, in, info, handler)
}

// Comms_ServiceDesc is the grpc.ServiceDesc for Comms service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Comms_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentero.Comms",
	HandlerType: (*CommsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CredentialSystem",
			Handler:    _Comms_CredentialSystem_Handler,
		},
		{
			MethodName: "GetContactAndPoliciesById",
			Handler:    _Comms_GetContactAndPoliciesById_Handler,
		},
		{
			MethodName: "GetContactsAndPoliciesByMobileNumber",
			Handler:    _Comms_GetContactsAndPoliciesByMobileNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agentero/agentero.proto",
}
